backend:
  name: git-gateway
  branch: main

media_folder: static/images
public_folder: /images

collections:
  - name: "projects"
    label: "Projects"
    folder: "src/content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subtitle", name: "subtitle", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Category", name: "category", widget: "string" }
      - { label: "Year", name: "year", widget: "string" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Color Theme", name: "color", widget: "select", options: ["gradient-purple", "gradient-dark", "bg-gray-100", "bg-gradient-to-br from-green-400 to-blue-500"] }
      - { label: "Technologies", name: "technologies", widget: "list" }
      - label: "Project Tree"
        name: "projectTree"
        widget: "object"
        fields:
          - { label: "Structure", name: "structure", widget: "list" }
          - { label: "Build Process", name: "buildProcess", widget: "text" }
      - { label: "Live Demo URL", name: "demoUrl", widget: "string", required: false }
      - { label: "Source Code URL", name: "sourceUrl", widget: "string", required: false }
      - { label: "Featured", name: "featured", widget: "boolean", default: false }
      - { label: "Order", name: "order", widget: "number", default: 0 }

  - name: "settings"
    label: "Settings"
    files:
      - label: "Personal Info"
        name: "personal"
        file: "src/content/personal.yml"
        fields:
          - { label: "Name", name: "name", widget: "string" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Bio", name: "bio", widget: "text" }
          - { label: "Profile Image", name: "profileImage", widget: "image" }
          - { label: "Email", name: "email", widget: "string" }
          - { label: "Phone", name: "phone", widget: "string", required: false }
          - label: "Social Links"
            name: "social"
            widget: "object"
            fields:
              - { label: "Twitter", name: "twitter", widget: "string", required: false }
              - { label: "LinkedIn", name: "linkedin", widget: "string", required: false }
              - { label: "GitHub", name: "github", widget: "string", required: false }
              - { label: "Dribbble", name: "dribbble", widget: "string", required: false }
              - { label: "Behance", name: "behance", widget: "string", required: false }
